### ISSUE TITLE
Curso de Java para iniciantes (plataforma: YouTube)

### ISSUE THREAD

**Issue by osksergio** [osksergio/java-my-study#1]
Curso de Java para iniciantes na plataforma YouTube. Segue o _link_ para acessar a playlist de vídeos:
https://www.youtube.com/watch?v=mRryrODqQcw&list=PLJ0AcghBBWSi6nK2CUkw9ngvwWB1gE8mL

- [ ] bem-vindo #01
- [ ] fundamentos de programação #02
- [ ] instalar o java jdk e intellij no windows (atualizado) - #03.1
- [ ] instalando java jdk e ide no macos #03.2
- [ ] primeiro programa java #04
- [ ] programação dinâmica com variáveis #05
- [ ] erros na programação (atualizado) #06
- [ ] funções #07
- [ ] argumentos #08
- [ ] projeto 01 e condições (atualizado) #09
- [ ] loops #10
- [ ] imports e packages #11
- [ ] java interativo #12
- [ ] tipos não primitivos #13
- [ ] escopo #14
- [ ] variável imutável #15
- [ ] visibilidade #16
- [ ] revisão primitivo #17
- [ ] casting #18
- [ ] manipulando strings #19
- [ ] comparando strings #20
- [ ] orientação a objetos intro #21
- [ ] oop métodos e propriedades #22
- [ ] oop getters e setters #23
- [ ] arrays - oop #24
- [ ] construtor - oop #25
- [ ] coleção. lista. arraylist - oop #26
- [ ] algoritmos #27
- [ ] ordenação #28
- [ ] comparando arrays #29
- [ ] preenchendo arrays - programação em java #30
- [ ] métodos do arraylist - programação em java #31
- [ ] ordenação e foreach de objetos - programação em java #32
- [ ] sobrecarga de métodos - programação em java #33
- [ ] to string - programação em java #34
- [ ] hashcode e equals - programação em java #35
- [ ] static - programação em java #36
- [ ] projeto resumão - programação em java #37
- [ ] projeto resumão (versão 2) - programação em java #38
- [ ] projeto resumão (versão 3) - programação em java #39
